import { useState, useEffect } from 'react'
import Head from 'next/head'
import Header from './header/Header'
import Footer from './footer/Footer'
import * as consult from './../services/ConsultServices'
import LoadingMain from './loading/LoadingMain'
import WhatsappMessage from './contact/WhatsappMessage'

const Layout = ({ children }) => {
    const [dataCompany, setDataCompany] = useState({})
    const [loadDataCompany, setLoadDataCompany] = useState(true)

    useEffect(() => {
        let isSubscribed = true
        const getDataCompany = async () => {
            try {
                const res = await consult.getAllData('empresa')
                if (res.status === 200) {
                    setDataCompany(res.data.data.attributes)
                }
            } catch (error) {
                console.log(error)
            }
            setLoadDataCompany(false)
        }

        if (isSubscribed) {
            setLoadDataCompany(true)
            getDataCompany()
        }

        return () => {
            isSubscribed = false
        }
    }, [])

    return (
        <>
            <Head>
                <title>Epic Travel Bolivia</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {
                loadDataCompany ? <LoadingMain /> : <>
                    <WhatsappMessage
                        dataCompany={{ state: dataCompany }}
                    />
                    <Header
                        dataCompany={{ state: dataCompany }}
                    />
                    {{ ...children, props: { ...children.props, dataCompany } }}
                    <Footer
                        dataCompany={{ state: dataCompany }}
                    />
                </>
            }
        </>
    )
}

export default Layout